/**
 * Team theme token sets — one per NFL team plus the neutral product-brand default.
 *
 * Each team carries luminance-tuned accent variants chosen for WCAG 2.2 AA
 * contrast (4.5:1 for text) against the light surface (#FFFFFF) and the dark
 * surface (#121418). Accents are derived from each club's primary brand color,
 * adjusted in lightness only (hue and saturation preserved) so team identity
 * survives the contrast fit. `accentContrast*` is the text color to set on
 * top of a filled accent, also AA-verified.
 *
 * Generated by /tmp/dcheck/gen-tokens.mjs; do not hand-edit hex values.
 * Regenerate if brand colors or surfaces change.
 */
export interface TeamThemeTokens {
  /** Canonical team abbreviation, e.g. 'KC'. Matches team_id in /api/v1. */
  teamId: string;
  name: string;
  abbr: string;
  /** Accent for light luminance. Contrast vs #FFFFFF: listed per team below. */
  accentLight: string;
  /** Accent for dark luminance. Contrast vs #121418: listed per team below. */
  accentDark: string;
  /** AA-verified text color on a filled accentLight. */
  accentContrastLight: string;
  /** AA-verified text color on a filled accentDark. */
  accentContrastDark: string;
}

export const TEAM_THEMES: TeamThemeTokens[] = [
  { teamId: 'ARI', name: 'Arizona Cardinals', abbr: 'ARI', accentLight: '#97233F', accentDark: '#D64F70', accentContrastLight: '#FFFFFF', accentContrastDark: '#000000' }, // 7.99:1 light / 4.58:1 dark
  { teamId: 'ATL', name: 'Atlanta Falcons', abbr: 'ATL', accentLight: '#A7194B', accentDark: '#E23F78', accentContrastLight: '#FFFFFF', accentContrastDark: '#000000' }, // 7.28:1 light / 4.58:1 dark
  { teamId: 'BAL', name: 'Baltimore Ravens', abbr: 'BAL', accentLight: '#241773', accentDark: '#7F6FE2', accentContrastLight: '#FFFFFF', accentContrastDark: '#000000' }, // 14.53:1 light / 4.63:1 dark
  { teamId: 'BUF', name: 'Buffalo Bills', abbr: 'BUF', accentLight: '#00338D', accentDark: '#2C78FF', accentContrastLight: '#FFFFFF', accentContrastDark: '#000000' }, // 11.30:1 light / 4.60:1 dark
  { teamId: 'CAR', name: 'Carolina Panthers', abbr: 'CAR', accentLight: '#007BBB', accentDark: '#0085CA', accentContrastLight: '#FFFFFF', accentContrastDark: '#000000' }, // 4.61:1 light / 4.57:1 dark
  { teamId: 'CHI', name: 'Chicago Bears', abbr: 'CHI', accentLight: '#0B162A', accentDark: '#4F7DD1', accentContrastLight: '#FFFFFF', accentContrastDark: '#000000' }, // 18.07:1 light / 4.55:1 dark
  { teamId: 'CIN', name: 'Cincinnati Bengals', abbr: 'CIN', accentLight: '#D83A04', accentDark: '#FB4F14', accentContrastLight: '#FFFFFF', accentContrastDark: '#000000' }, // 4.64:1 light / 5.47:1 dark
  { teamId: 'CLE', name: 'Cleveland Browns', abbr: 'CLE', accentLight: '#311D00', accentDark: '#B86D00', accentContrastLight: '#FFFFFF', accentContrastDark: '#000000' }, // 16.08:1 light / 4.59:1 dark
  { teamId: 'DAL', name: 'Dallas Cowboys', abbr: 'DAL', accentLight: '#003594', accentDark: '#2B77FF', accentContrastLight: '#FFFFFF', accentContrastDark: '#000000' }, // 10.84:1 light / 4.55:1 dark
  { teamId: 'DEN', name: 'Denver Broncos', abbr: 'DEN', accentLight: '#D83A04', accentDark: '#FB4F14', accentContrastLight: '#FFFFFF', accentContrastDark: '#000000' }, // 4.64:1 light / 5.47:1 dark
  { teamId: 'DET', name: 'Detroit Lions', abbr: 'DET', accentLight: '#0076B6', accentDark: '#0085CD', accentContrastLight: '#FFFFFF', accentContrastDark: '#000000' }, // 4.92:1 light / 4.60:1 dark
  { teamId: 'GB', name: 'Green Bay Packers', abbr: 'GB', accentLight: '#203731', accentDark: '#50897A', accentContrastLight: '#FFFFFF', accentContrastDark: '#000000' }, // 12.71:1 light / 4.57:1 dark
  { teamId: 'HOU', name: 'Houston Texans', abbr: 'HOU', accentLight: '#03202F', accentDark: '#0D87C6', accentContrastLight: '#FFFFFF', accentContrastDark: '#000000' }, // 16.78:1 light / 4.65:1 dark
  { teamId: 'IND', name: 'Indianapolis Colts', abbr: 'IND', accentLight: '#002C5F', accentDark: '#0679FF', accentContrastLight: '#FFFFFF', accentContrastDark: '#000000' }, // 13.77:1 light / 4.55:1 dark
  { teamId: 'JAX', name: 'Jacksonville Jaguars', abbr: 'JAX', accentLight: '#00677F', accentDark: '#008AAA', accentContrastLight: '#FFFFFF', accentContrastDark: '#000000' }, // 6.47:1 light / 4.58:1 dark
  { teamId: 'KC', name: 'Kansas City Chiefs', abbr: 'KC', accentLight: '#E31837', accentDark: '#EA3A55', accentContrastLight: '#FFFFFF', accentContrastDark: '#000000' }, // 4.72:1 light / 4.60:1 dark
  { teamId: 'LAC', name: 'Los Angeles Chargers', abbr: 'LAC', accentLight: '#007BBE', accentDark: '#0085CE', accentContrastLight: '#FFFFFF', accentContrastDark: '#000000' }, // 4.59:1 light / 4.61:1 dark
  { teamId: 'LAR', name: 'Los Angeles Rams', abbr: 'LAR', accentLight: '#003594', accentDark: '#2B77FF', accentContrastLight: '#FFFFFF', accentContrastDark: '#000000' }, // 10.84:1 light / 4.55:1 dark
  { teamId: 'LV', name: 'Las Vegas Raiders', abbr: 'LV', accentLight: '#000000', accentDark: '#808080', accentContrastLight: '#FFFFFF', accentContrastDark: '#000000' }, // 21.00:1 light / 4.67:1 dark
  { teamId: 'MIA', name: 'Miami Dolphins', abbr: 'MIA', accentLight: '#00828A', accentDark: '#008E97', accentContrastLight: '#FFFFFF', accentContrastDark: '#000000' }, // 4.61:1 light / 4.67:1 dark
  { teamId: 'MIN', name: 'Minnesota Vikings', abbr: 'MIN', accentLight: '#4F2683', accentDark: '#9767D3', accentContrastLight: '#FFFFFF', accentContrastDark: '#000000' }, // 10.84:1 light / 4.56:1 dark
  { teamId: 'NE', name: 'New England Patriots', abbr: 'NE', accentLight: '#002244', accentDark: '#007DF9', accentContrastLight: '#FFFFFF', accentContrastDark: '#000000' }, // 16.00:1 light / 4.65:1 dark
  { teamId: 'NO', name: 'New Orleans Saints', abbr: 'NO', accentLight: '#8E7137', accentDark: '#D3BC8D', accentContrastLight: '#FFFFFF', accentContrastDark: '#000000' }, // 4.60:1 light / 9.96:1 dark
  { teamId: 'NYG', name: 'New York Giants', abbr: 'NYG', accentLight: '#0B2265', accentDark: '#5078EC', accentContrastLight: '#FFFFFF', accentContrastDark: '#000000' }, // 14.68:1 light / 4.60:1 dark
  { teamId: 'NYJ', name: 'New York Jets', abbr: 'NYJ', accentLight: '#125740', accentDark: '#1E906A', accentContrastLight: '#FFFFFF', accentContrastDark: '#000000' }, // 8.53:1 light / 4.61:1 dark
  { teamId: 'PHI', name: 'Philadelphia Eagles', abbr: 'PHI', accentLight: '#004C54', accentDark: '#008D9B', accentContrastLight: '#FFFFFF', accentContrastDark: '#000000' }, // 9.71:1 light / 4.64:1 dark
  { teamId: 'PIT', name: 'Pittsburgh Steelers', abbr: 'PIT', accentLight: '#9C6C00', accentDark: '#FFB612', accentContrastLight: '#FFFFFF', accentContrastDark: '#000000' }, // 4.61:1 light / 10.49:1 dark
  { teamId: 'SF', name: 'San Francisco 49ers', abbr: 'SF', accentLight: '#AA0000', accentDark: '#FE0000', accentContrastLight: '#FFFFFF', accentContrastDark: '#000000' }, // 7.75:1 light / 4.58:1 dark
  { teamId: 'SEA', name: 'Seattle Seahawks', abbr: 'SEA', accentLight: '#002244', accentDark: '#007DF9', accentContrastLight: '#FFFFFF', accentContrastDark: '#000000' }, // 16.00:1 light / 4.65:1 dark
  { teamId: 'TB', name: 'Tampa Bay Buccaneers', abbr: 'TB', accentLight: '#D50A0A', accentDark: '#F52727', accentContrastLight: '#FFFFFF', accentContrastDark: '#000000' }, // 5.42:1 light / 4.57:1 dark
  { teamId: 'TEN', name: 'Tennessee Titans', abbr: 'TEN', accentLight: '#0C2340', accentDark: '#377FD9', accentContrastLight: '#FFFFFF', accentContrastDark: '#000000' }, // 15.79:1 light / 4.57:1 dark
  { teamId: 'WAS', name: 'Washington Commanders', abbr: 'WAS', accentLight: '#5A1414', accentDark: '#D85050', accentContrastLight: '#FFFFFF', accentContrastDark: '#000000' }, // 13.59:1 light / 4.55:1 dark
];

/** Neutral product-brand default accent (non-members, or members with accent source 'Neutral'). */
export const NEUTRAL_THEME: TeamThemeTokens = {
  teamId: 'neutral', name: 'Purging Light', abbr: 'PL', accentLight: '#1D4ED8', accentDark: '#5279E8', accentContrastLight: '#FFFFFF', accentContrastDark: '#000000',
}; // 6.70:1 light / 4.62:1 dark

const BY_ID = new Map<string, TeamThemeTokens>(TEAM_THEMES.map((t) => [t.teamId, t]));

/** Look up a team's token set by id; case-insensitive. Returns undefined for unknown ids. */
export function getTeamTheme(teamId: string): TeamThemeTokens | undefined {
  return BY_ID.get(teamId.toUpperCase());
}
